---
# Replace <DOMAIN> below with your domain (e.g. example.com)
# or your tailnet domain (e.g. tail12345.ts.net) if not using a custom domain

pageInfo:
  title: Box
  description: Welcome to your new dashboard!
  navLinks:
    - title: GitHub
      path: https://github.com/tjsheppard/box

appConfig:
  theme: default
  layout: vertical
  iconSize: "large"
  language: "en"

sections:
  - name: Media
    icon: fas fa-play
    items:
      - title: Jellyfin
        description: Watch films and shows
        icon: far fa-play
        url: https://jellyfin.<DOMAIN>
        target: newtab
      - title: File Browser
        description: Manage folders and files
        icon: far fa-folder
        url: https://files.<DOMAIN>
        target: newtab
  - name: Downloads
    icon: fas fa-download
    items:
      - title: Deluge
        description: Torrent downloader
        icon: far fa-download
        url: https://deluge.<DOMAIN>
        target: newtab
      - title: Prowlarr
        description: Torrent indexer
        icon: far fa-database
        url: https://prowlarr.<DOMAIN>
        target: newtab
      - title: Sonarr
        description: Manage shows
        icon: far fa-tv
        url: https://sonarr.<DOMAIN>
        target: newtab
      - title: Radarr
        description: Manage films
        icon: far fa-film
        url: https://radarr.<DOMAIN>
        target: newtab
  - name: Management
    icon: fas fa-cog
    items:
      - title: Portainer
        description: Manage Docker containers
        icon: far fa-box
        url: https://portainer.<DOMAIN>
        target: newtab
      - title: Dashy
        description: This dashboard
        icon: far fa-home
        url: https://dashy.<DOMAIN>
        target: newtab
      - title: Tailscale
        description: Remote connection
        icon: far fa-cloud
        url: https://login.tailscale.com/admin/machines
        target: newtab
